name: transformations tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  base-tests:
    name: Base install tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install .

    - name: Run tests
      run: |
        find src/transformations -maxdepth 1 -type f -name "*_test.py" -exec python {} \;

  quat-tests:
    name: quat install tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install quat dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install .[quat]

    - name: Run tests
      run: |
        find src/transformations -maxdepth 1 -type f -name "*_test.py" -exec python {} \;

  jax-tests:
    name: JAX install tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install JAX dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install .[jax]

    - name: Run tests
      run: |
        find src -type f -name "*_test.py" -exec python {} \;
